import '../models/dare.dart';

const List<Dare> kBuiltinDares = [
  Dare(id: 'builtin_0',  text: 'Doe 10 push-ups'),
  Dare(id: 'builtin_1',  text: 'Bel iemand op en zing een liedje'),
  Dare(id: 'builtin_2',  text: 'Wissel van plek met iemand anders'),
  Dare(id: 'builtin_3',  text: 'Drink je glas in één keer leeg'),
  Dare(id: 'builtin_4',  text: 'Vertel een genant geheim'),
  Dare(id: 'builtin_5',  text: 'Doe een dans die iedereen moet natansen'),
  Dare(id: 'builtin_6',  text: 'Spreek de rest van de ronde met een accent'),
  Dare(id: 'builtin_7',  text: 'Geef iemand een compliment dat je normaal nooit zou zeggen'),
  Dare(id: 'builtin_8',  text: 'Laat iemand anders je telefoon één minuut vasthouden'),
  Dare(id: 'builtin_9',  text: 'Doe 30 seconden lang niets en zeg niets'),
  Dare(id: 'builtin_10', text: 'Doe 20 squats'),
  Dare(id: 'builtin_11', text: 'Zing het refrein van het laatste liedje dat je geluisterd hebt'),
  Dare(id: 'builtin_12', text: 'Spreek drie zinnen achter elkaar uitsluitend in rijm'),
  Dare(id: 'builtin_13', text: 'Doe een plank van 30 seconden'),
  Dare(id: 'builtin_14', text: 'Beschrijf jezelf in drie woorden — de anderen kiezen de woorden'),
  Dare(id: 'builtin_15', text: 'Doe alsof je een reclame maakt voor het eerste object dat je ziet'),
  Dare(id: 'builtin_16', text: 'Stuur een random emoji naar de laatste persoon in je chats'),
  Dare(id: 'builtin_17', text: 'Doe de slechtste robot-dans die je kunt'),
  Dare(id: 'builtin_18', text: 'Vertel iets dat niemand hier van je weet'),
  Dare(id: 'builtin_19', text: 'Houd 30 seconden lang een gekke pose vast'),
  Dare(id: 'builtin_20', text: 'Imiteer iemand in de groep totdat iemand raadt wie je bent'),
  Dare(id: 'builtin_21', text: 'Zeg drie dingen die je leuk vindt aan de persoon links van je'),
  Dare(id: 'builtin_22', text: 'Doe 15 jumping jacks'),
  Dare(id: 'builtin_23', text: 'Zeg "banaan" na elke zin die je zegt voor de volgende ronde'),
  Dare(id: 'builtin_24', text: 'Vertel je meest gênante sportmoment'),
  Dare(id: 'builtin_25', text: 'Maak een geluidsimitatie van een dier — de rest raadt welk'),
  Dare(id: 'builtin_26', text: 'Laat iemand anders een berichtje sturen via jouw telefoon'),
  Dare(id: 'builtin_27', text: 'Doe alsof je een nieuwslezer bent en vertel het laatste nieuws'),
  Dare(id: 'builtin_28', text: 'Noem 10 landen in 10 seconden'),
  Dare(id: 'builtin_29', text: 'Beschrijf een film zonder de titel te noemen — de rest raadt'),
  Dare(id: 'builtin_30', text: 'Ga 30 seconden lang in een denkbeeldige stoel zitten (luchtstoel)'),
  Dare(id: 'builtin_31', text: 'Vertel je slechtste grap'),
  Dare(id: 'builtin_32', text: 'Doe de macarena terwijl je de tekst zingt'),
  Dare(id: 'builtin_33', text: 'Toon de meest pijnlijke autocorrect-fout op je telefoon'),
  Dare(id: 'builtin_34', text: 'Zeg het alfabet achterstevoren zo snel mogelijk'),
  Dare(id: 'builtin_35', text: 'Houd een minuut lang een gesprek zonder te lachen'),
  Dare(id: 'builtin_36', text: 'Maak een selfie met een rare gezichtsuitdrukking en toon die aan de groep'),
  Dare(id: 'builtin_37', text: 'Doe alsof je een kok bent en beschrijf het lekkerste gerecht dat je ooit at'),
  Dare(id: 'builtin_38', text: 'Zing "Happy Birthday" in opera-stijl'),
  Dare(id: 'builtin_39', text: 'Neem de rest van de ronde elke zin op fluistertoon'),
];
